name: Playwright Tests

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 and run tests
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo docker rm -f playwright-container || true
            sudo docker pull nishipatil/playwright-tests:v1

            sudo docker run \
            -v ~/playwright-report:/app/playwright-report \
            --name playwright-container \
            nishipatil/playwright-tests:v1

            echo "===== DEBUG START ====="
            echo "Current directory:"
            pwd

            echo "Home directory content:"
            ls -la ~
            echo "Report folder content:"
            ls -la ~/playwright-report

            echo "===== DEBUG END ====="

            echo "Checking report folder..."
            ls -la ~/playwright-report

      - name: Copy report from EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "playwright-report"
          target: "./"

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/