name: Playwright Tests

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 and run tests
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo docker rm -f playwright-container || true
            sudo docker pull nishipatil/playwright-tests:latest
            sudo docker run --name playwright-container nishipatil/playwright-tests:latest
            sudo docker logs playwright-container